# -*- coding: utf-8 -*-
"""ClimateRiskLossModel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15BnlPk9I0OTLsKIiSmm2-OUID-Cr0fma
"""

import pandas as pd
import glob

files = glob.glob("/content/drive/MyDrive/Climate Risk and Insurance Loss Modeling/StormEvents_details-ftp_v1.0_d*_c*.csv")

dfs = [pd.read_csv(f, low_memory=False) for f in files]

noaa = pd.concat(dfs, ignore_index=True)

print(noaa.shape)
noaa.head()

def convert_damage(val):
    if pd.isna(val):
        return 0
    val = str(val).strip()

    if val.endswith('K'):
        return float(val[:-1]) * 1_000
    elif val.endswith('M'):
        return float(val[:-1]) * 1_000_000
    elif val.endswith('B'):
        return float(val[:-1]) * 1_000_000_000
    else:
        try:
            return float(val)
        except:
            return 0

noaa['damage_property'] = noaa['DAMAGE_PROPERTY'].apply(convert_damage)
noaa['damage_crops'] = noaa['DAMAGE_CROPS'].apply(convert_damage)

noaa['total_damage'] = noaa['damage_property'] + noaa['damage_crops']

noaa['year'] = pd.to_datetime(noaa['BEGIN_DATE_TIME'], errors='coerce').dt.year

major_events = ['Hurricane', 'Flood', 'Tornado', 'Storm Surge', 'Wildfire']
noaa = noaa[noaa['EVENT_TYPE'].isin(major_events)]

noaa_grouped = noaa.groupby(['STATE','year']).agg({
    'total_damage':'sum',
    'EVENT_TYPE':'count'
}).rename(columns={'EVENT_TYPE':'event_count'}).reset_index()

noaa_grouped.head()

noaa_grouped.describe()

zillow = pd.read_csv("/content/drive/MyDrive/Climate Risk and Insurance Loss Modeling/County_zhvi_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv")

zillow.columns

zillow['STATE'] = zillow['StateName']

zillow_long = zillow.melt(
    id_vars=['STATE'],
    var_name='date',
    value_name='home_value'
)

zillow_long['date'] = pd.to_datetime(zillow_long['date'], errors='coerce')

zillow_long['year'] = zillow_long['date'].dt.year

zillow_long['year'] = zillow_long['year'].astype('Int64')

zillow_state = zillow_long.groupby(['STATE','year'])['home_value'].mean().reset_index()

zillow_state.head()

zillow_state.describe()

pop = pd.read_csv("/content/drive/MyDrive/Climate Risk and Insurance Loss Modeling/DECENNIALDHC2020.P1-2026-03-26T162154.csv")
housing = pd.read_csv("/content/drive/MyDrive/Climate Risk and Insurance Loss Modeling/DECENNIALDHC2020.H1-2026-03-26T162235.csv")

pop.head()

housing.head()

pop_t = pop.T.reset_index()
pop_t.columns = ['STATE', 'population']
pop_t = pop_t.iloc[1:]

housing_t = housing.T.reset_index()
housing_t.columns = ['STATE', 'housing_units']
housing_t = housing_t.iloc[1:]

census = pd.merge(pop_t, housing_t, on='STATE')

census['STATE'] = census['STATE'].str.upper().str.strip()

census['population'] = census['population'].astype(str).str.replace(',', '', regex=False).str.strip()
census['housing_units'] = census['housing_units'].astype(str).str.replace(',', '', regex=False).str.strip()

census['population'] = pd.to_numeric(census['population'], errors='coerce')
census['housing_units'] = pd.to_numeric(census['housing_units'], errors='coerce')

census.head()

fema = pd.read_csv("/content/drive/MyDrive/Climate Risk and Insurance Loss Modeling/DisasterDeclarationsSummaries.csv")
fema.columns

fema['year'] = pd.to_datetime(fema['declarationDate'], errors='coerce').dt.year

fema_grouped = fema.groupby(['state', 'year']).size().reset_index(name='disaster_count')

fema_grouped.rename(columns={'state': 'STATE'}, inplace=True)

fema_grouped['STATE'] = fema_grouped['STATE'].str.upper().str.strip()

fema_grouped.head()

state_map = {
    'AL': 'ALABAMA','AK': 'ALASKA','AZ': 'ARIZONA','AR': 'ARKANSAS','CA': 'CALIFORNIA',
    'CO': 'COLORADO','CT': 'CONNECTICUT','DE': 'DELAWARE','FL': 'FLORIDA','GA': 'GEORGIA',
    'HI': 'HAWAII','ID': 'IDAHO','IL': 'ILLINOIS','IN': 'INDIANA','IA': 'IOWA',
    'KS': 'KANSAS','KY': 'KENTUCKY','LA': 'LOUISIANA','ME': 'MAINE','MD': 'MARYLAND',
    'MA': 'MASSACHUSETTS','MI': 'MICHIGAN','MN': 'MINNESOTA','MS': 'MISSISSIPPI',
    'MO': 'MISSOURI','MT': 'MONTANA','NE': 'NEBRASKA','NV': 'NEVADA','NH': 'NEW HAMPSHIRE',
    'NJ': 'NEW JERSEY','NM': 'NEW MEXICO','NY': 'NEW YORK','NC': 'NORTH CAROLINA',
    'ND': 'NORTH DAKOTA','OH': 'OHIO','OK': 'OKLAHOMA','OR': 'OREGON','PA': 'PENNSYLVANIA',
    'RI': 'RHODE ISLAND','SC': 'SOUTH CAROLINA','SD': 'SOUTH DAKOTA','TN': 'TENNESSEE',
    'TX': 'TEXAS','UT': 'UTAH','VT': 'VERMONT','VA': 'VIRGINIA','WA': 'WASHINGTON',
    'WV': 'WEST VIRGINIA','WI': 'WISCONSIN','WY': 'WYOMING'
}

zillow_state['STATE'] = zillow_state['STATE'].map(state_map)

fema_grouped['STATE'] = fema_grouped['STATE'].map(state_map)

merged = noaa_grouped.merge(
    zillow_state,
    on=['STATE','year'],
    how='left'
)

merged = merged.merge(
    fema_grouped,
    on=['STATE','year'],
    how='left'
)

merged = merged.merge(
    census,
    on='STATE',
    how='left'
)

merged['STATE'] = merged['STATE'].str.upper().str.strip()

merged['disaster_count'] = merged['disaster_count'].fillna(0)

merged.head()

merged['exposure'] = merged['home_value'] * merged['housing_units']

merged['damage_per_capita'] = merged['total_damage'] / merged['population']

merged['risk_score'] = (
    merged['total_damage'] * 0.5 +
    merged['event_count'] * 0.2 +
    merged['disaster_count'] * 0.1 +
    merged['exposure'] * 0.2
)

merged[['STATE','year','risk_score']].head()

merged['norm_damage'] = merged['total_damage'] / merged['total_damage'].max()
merged['norm_events'] = merged['event_count'] / merged['event_count'].max()
merged['norm_fema'] = merged['disaster_count'] / merged['disaster_count'].max()
merged['norm_exposure'] = merged['exposure'] / merged['exposure'].max()

merged['risk_score_norm'] = (
    merged['norm_damage'] * 0.4 +
    merged['norm_events'] * 0.2 +
    merged['norm_fema'] * 0.1 +
    merged['norm_exposure'] * 0.3
)

merged[['STATE','year','risk_score','risk_score_norm']].head()

ml_data = merged[['norm_damage','norm_events','norm_fema','norm_exposure','risk_score_norm']].dropna()

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

X = ml_data[['norm_damage','norm_events','norm_fema','norm_exposure']]
y = ml_data['risk_score_norm']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = RandomForestRegressor(random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("MSE:", mse)
print("R2:", r2)

merged = merged.sort_values(['STATE','year'])

merged['next_risk'] = merged.groupby('STATE')['risk_score_norm'].shift(-1)

ml_data = merged[['norm_damage','norm_events','norm_fema','norm_exposure','next_risk']].dropna()

X = ml_data[['norm_damage','norm_events','norm_fema','norm_exposure']]
y = ml_data['next_risk']

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = RandomForestRegressor(random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("MSE:", mean_squared_error(y_test, y_pred))
print("R2:", r2_score(y_test, y_pred))

importance = pd.Series(model.feature_importances_, index=X.columns)
print(importance.sort_values(ascending=False))

merged.to_csv("climate_risk_final.csv", index=False)

from google.colab import files
files.download("climate_risk_final.csv")